fbi-service:
  ribbon:
    listOfServers: localhost:8082
spring:
  application:
    name: hippo-service
  zipkin:
    base-url: http://gateway-server.service.consul:9000

logging:
  level.org.springframework.cloud: DEBUG